{{ include "common.storage.hostPathValidate" .Values }}
apiVersion: {{ template "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  labels:
    app: {{ template "common.names.name" . }}
    chart: {{ template "common.names.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  replicas: {{ (default 1 .Values.replicas) }}
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      app: {{ template "common.names.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "common.names.fullname" . }}
      labels:
        app: {{ template "common.names.name" . }}
        release: {{ .Release.Name }}
        {{- include "common.labels.selectorLabels" . | nindent 8 }}
      annotations: {{ include "common.annotations" . | nindent 8 }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      hostname: {{ .Release.Name }}
      containers:
        - name: {{ .Chart.Name }}
          {{ include "common.resources.limitation" . | nindent 10 }}
          {{ include "common.containers.imageConfig" .Values.image | nindent 10 }}
          volumeMounts: {{ include "common.storage.configureAppVolumeMountsInContainer" .Values | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ 5002 }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          livenessProbe:
            tcpSocket:
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            tcpSocket:
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          env:
            {{ $envList := (default list .Values.environmentVariables) }}
            {{ $envList = mustAppend $envList (dict "name" "PORT_HTTPS" "value" "") }}
            {{ $envList = mustAppend $envList (dict "name" "MIN_WAIT_MINUTES_TO_NOTIFY_SAME_GROUP" "value" (.Values.minWaitMinutesToNotifySameGroup | int))) }}
            {{ $envList = mustAppend $envList (dict "name" "SMS_CLIENT_ID" "value" .Values.sms_client_id) }}
            {{ $envList = mustAppend $envList (dict "name" "SMS_CLIENT_SECRET" "value" .Values.sms_client_secret) }}
            {{ $envList = mustAppend $envList (dict "name" "SMS_SENDER_NR" "value" .Values.sms_sender_nr) }}
            {{ $envList = mustAppend $envList (dict "name" "SMS_VALIDITY_HOURS" "value" (printf "%d" (.Values.sms_validity_hours | int))) }}
            {{ $envList = mustAppend $envList (dict "name" "SMS_WAIT_FOR_STATUS" "value" (printf "%d" (.Values.sms_wait_for_status | int))) }}
            {{ $envList = mustAppend $envList (dict "name" "EMAIL_SMTP_SENDER_EMAIL" "value" .Values.email_smtp_sender_email) }}
            {{ $envList = mustAppend $envList (dict "name" "EMAIL_SMTP_USERNAME" "value" .Values.email_smtp_username) }}
            {{ $envList = mustAppend $envList (dict "name" "EMAIL_SMTP_PASSWORD" "value" .Values.email_smtp_password) }}
            {{ $envList = mustAppend $envList (dict "name" "EMAIL_SMTP_USE_SSL" "value" (printf "%d" (.Values.email_smtp_use_ssl | int))) }}
            {{ $envList = mustAppend $envList (dict "name" "EMAIL_SMTP_SERVER_HOST" "value" .Values.email_smtp_server_host) }}
            {{ $envList = mustAppend $envList (dict "name" "EMAIL_SMTP_SERVER_PORT" "value" (printf "%d" (.Values.email_smtp_server_port | int))) }}
            {{ $envList = mustAppend $envList (dict "name" "EMAIL_POSTMASTER_ADDRESS" "value" .Values.email_postmaster_address) }}
            {{ $envList = mustAppend $envList (dict "name" "XXXSSL_CERT_SUBJ" "value" "") }}
            {{ $envList = mustAppend $envList (dict "name" "PUID" "value" (printf "%d" (.Values.ownerUID | int))) }}
            {{ $envList = mustAppend $envList (dict "name" "PGID" "value" (printf "%d" (.Values.ownerGID | int))) }}
            {{ include "common.containers.environmentVariables" (dict "environmentVariables" $envList) | nindent 12 }}
      {{ include "common.networking.dnsConfiguration" .Values | nindent 6 }}
      volumes: {{ include "common.storage.configureAppVolumes" .Values | nindent 8 }}
