name: firenotifier
description: Notification service
type: application
version: 2024.1.5
apiVersion: v2
appVersion: 2024.1.5
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: as19git67
    url: https://www.schegg.de/
    email: schliesst06.erweitern@icloud.com
dependencies:
  - name: common
    repository: file://../../../common/2304.0.1
    version: 2304.0.1
home: https://www.schegg.de/
icon: https://raw.githubusercontent.com/as19git67/firenotifier/main/fire-alarm.png
keywords:
  - firefighter
  - notification
  - alarm
  - feuerwehr
sources:
  - https://github.com/as19git67/firecharts
  - https://github.com/as19git67/firenotifier
